In [2]:
import numpy as np

a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
a.shape

(4,)

In [3]:
a.ndim

1

In [ ]:
b=np.array([[1,2,3,4],[6,7,8,9]])
b.shape

(2, 4)

In [8]:
b.ndim

2

In [13]:
import numpy as np

c = np.array([[[1,2,3,4],[6,7,8,9]],
    [[1,2,3,4],[5,6,9,3]],[[1,2,3,4],[6,7,8,9]]])
print(c)


[[[1 2 3 4]
  [6 7 8 9]]

 [[1 2 3 4]
  [5 6 9 3]]

 [[1 2 3 4]
  [6 7 8 9]]]


In [14]:
c.shape

(3, 2, 4)

In [15]:
c.ndim

3

In [16]:
b=np.array([[1,2,3,4],[6,7,8,9]])
d=b**2
print(d)

[[ 1  4  9 16]
 [36 49 64 81]]


In [22]:
np.zeros((3,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [23]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.random.rand(3,3)

array([[0.42096171, 0.55252291, 0.78403649],
       [0.01117296, 0.14194995, 0.36949168],
       [0.39299135, 0.19503158, 0.05340466]])

In [28]:
a=np.array([1,2,3,4])
b=np.array([1,4,8,4])
c=a+b
print(c)

[ 2  6 11  8]


In [4]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [7]:
np.ones((4,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [12]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [14]:
print(np.full((2,2),2))

[[2 2]
 [2 2]]


In [15]:
print(np.full((2,3),3))

[[3 3 3]
 [3 3 3]]


In [ ]:
print(np.arange(0,10,2))

[0 2 4 6 8]


In [21]:
print(np.linspace(0,1,5))

[0.   0.25 0.5  0.75 1.  ]


In [23]:
a=np.array([1,2,5,6,11,12])
print(a)

[ 1  2  5  6 11 12]


In [24]:
b=np.array([[1,2],[3,4],[5,6]])
print(b)


[[1 2]
 [3 4]
 [5 6]]


In [27]:
print(np.zeros((2,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [25]:
print(np.zeros((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [28]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [30]:
print(np.eye(2))

[[1. 0.]
 [0. 1.]]


In [31]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [33]:
print(np.full((2,3),7))

[[7 7 7]
 [7 7 7]]


In [45]:
print(np.arange(0,13,2))

[ 0  2  4  6  8 10 12]


In [37]:
print(np.linspace(1,11,6))

[ 1.  3.  5.  7.  9. 11.]


In [40]:
a=np.array(["a","b","c"])
print(a)
print(a.dtype)
print(a.shape)

['a' 'b' 'c']
<U1
(3,)


In [43]:
c=np.array([1,2,4,5,6])
print(c)
print(c.dtype)
print(a.ndim)

[1 2 4 5 6]
int64
1


In [44]:
b=np.arange(1,9)
print(b)

[1 2 3 4 5 6 7 8]


In [46]:
b.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [48]:
b.reshape(8,)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [50]:
c=np.array([1,2,3,4])
d=np.array([5,6,7,8])

print(c+d)
print(c*d)
print(d**2)

[ 6  8 10 12]
[ 5 12 21 32]
[25 36 49 64]


In [68]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a[0,0])
print(a[0,1])
print(a[0,2])
print(a[1,0])
print(a[1,1])
print(a[1,2])


print(a[:,1])
print(a[:])

[[1 2 3]
 [4 5 6]]
1
2
3
4
5
6
[2 5]
[[1 2 3]
 [4 5 6]]


In [59]:
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.sum(a))
print(np.max(a))
print(np.min(a))

3.5
3.5
1.707825127659933
21
6
1


In [62]:
np.random.rand(2,3)

array([[0.00147448, 0.93165239, 0.61345813],
       [0.03890522, 0.16028652, 0.31046564]])

In [65]:
a=np.random.randn(2,3)
print(a)
print(np.mean(a))

[[-0.76404051  2.07070878 -0.63169913]
 [ 0.38113172  1.681428   -0.05893583]]
0.4464321723622024


In [66]:
np.random.randint(0,10)

8

In [67]:
import numpy as np

a = np.random.randn(2, 3)
print("Small sample:\n", a)
print("Mean of small sample:", np.mean(a))

b = np.random.randn(1000000)  # 1 million samples
print("\nLarge sample mean:", np.mean(b))
print("Large sample std:", np.std(b))

Small sample:
 [[-0.0419547   0.70019401  0.15546398]
 [-0.34417419  0.1500213  -1.69804092]]
Mean of small sample: -0.17974842064936758

Large sample mean: 7.851253991799137e-05
Large sample std: 1.0011407879461258
