In [19]:
import numpy as np

a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [2]:
a.shape

(4,)

In [3]:
a.ndim

1

In [7]:


b=np.array([[1,2,3,4],[6,7,8,9]])
b.shape

(2, 4)

In [8]:
b.ndim

2

In [13]:
import numpy as np

c = np.array([[[1,2,3,4],[6,7,8,9]],
    [[1,2,3,4],[5,6,9,3]],[[1,2,3,4],[6,7,8,9]]])
print(c)


[[[1 2 3 4]
  [6 7 8 9]]

 [[1 2 3 4]
  [5 6 9 3]]

 [[1 2 3 4]
  [6 7 8 9]]]


In [14]:
c.shape

(3, 2, 4)

In [15]:
c.ndim

3

In [16]:
b=np.array([[1,2,3,4],[6,7,8,9]])
d=b**2
print(d)

[[ 1  4  9 16]
 [36 49 64 81]]


In [22]:
np.zeros((3,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [23]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.random.rand(3,3)

array([[0.42096171, 0.55252291, 0.78403649],
       [0.01117296, 0.14194995, 0.36949168],
       [0.39299135, 0.19503158, 0.05340466]])

In [28]:
a=np.array([1,2,3,4])
b=np.array([1,4,8,4])
c=a+b
print(c)

[ 2  6 11  8]
